package game.maps.types;

public enum RoomType {
    FLOOR, ROOM_ONE, ROOM_TWO, ROOM_THREE, ROOM_FOUR, ROOM_FIVE, ROOM_SIX, ROOM_SEVEN, ROOM_EIGHT,
    GRASS_FLOOR, SCENE1, SCENE2, SCENE3, SCENE4
}
